"""Tests for lib/xml_doc.py -- recursive nested XML document model.

Covers build, parse, serialize, mutation helpers, path-based navigation,
walk_sections, get_section_paths, and round-trip fidelity at 1-3 nesting
levels. Verifies that build -> serialize -> parse yields identical structure.
"""

import os
import sys
import tempfile

import pytest

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from lib.xml_doc import (
    add_section,
    build_xml_doc,
    get_section_paths,
    get_section_slugs,
    parse_xml_doc,
    serialize_xml_doc,
    update_section_body,
    update_section_refs,
    walk_sections,
)

SAMPLE_HEADER = """<!-- This file is auto-generated by /mg:auto-doc -->
<!-- DIATAXIS: how-to -->
<!-- AUDIENCE: devops -->

# Operations Guide"""


# ---------------------------------------------------------------------------
# Flat sections (depth 1) -- backward compatibility
# ---------------------------------------------------------------------------

FLAT_SECTIONS = [
    {
        "slug": "monitoring-alerting",
        "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nThe ETL run log tracks all pipeline executions.",
    },
    {
        "slug": "deployment",
        "body": "<!-- section: deployment -->\n## Deployment\n\nDeploy via CI/CD pipeline.",
    },
]


# ---------------------------------------------------------------------------
# Nested sections (depth 2)
# ---------------------------------------------------------------------------

NESTED_SECTIONS_2 = [
    {
        "slug": "monitoring-alerting",
        "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nIntro to monitoring.",
        "children": [
            {
                "slug": "etl-run-logging",
                "body": "<!-- section: etl-run-logging -->\n### ETL Run Logging\n\nLogs all pipeline runs.",
                "children": [],
            },
            {
                "slug": "alert-routing",
                "body": "<!-- section: alert-routing -->\n### Alert Routing\n\nRoutes alerts to PagerDuty.",
                "children": [],
            },
        ],
    },
    {
        "slug": "deployment",
        "body": "<!-- section: deployment -->\n## Deployment\n\nDeploy via CI/CD pipeline.",
        "children": [],
    },
]


# ---------------------------------------------------------------------------
# Nested sections (depth 3)
# ---------------------------------------------------------------------------

NESTED_SECTIONS_3 = [
    {
        "slug": "monitoring-alerting",
        "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nIntro to monitoring.",
        "children": [
            {
                "slug": "etl-run-logging",
                "body": "<!-- section: etl-run-logging -->\n### ETL Run Logging\n\nLogs all pipeline runs.",
                "children": [
                    {
                        "slug": "artifact-format",
                        "body": "<!-- section: artifact-format -->\n#### Artifact Format\n\nJSON artifact per run.",
                        "children": [],
                    },
                ],
            },
        ],
    },
]


def _round_trip(sections, audience="devops", diataxis="how-to",
                header=SAMPLE_HEADER, title="Operations Guide"):
    """Build -> serialize -> parse helper returning parsed doc dict."""
    tree = build_xml_doc(audience, diataxis, header, sections, title=title)
    with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
        path = f.name
    try:
        serialize_xml_doc(tree, path)
        return parse_xml_doc(path)
    finally:
        os.unlink(path)


# ===================================================================
# Build & Parse
# ===================================================================

class TestBuildAndParse:
    """build_xml_doc + parse_xml_doc round-trip for flat and nested."""

    def test_round_trip_flat_structure(self):
        """Flat sections (no children key) still work -- backward compat."""
        doc = _round_trip(FLAT_SECTIONS)

        assert doc["audience"] == "devops"
        assert doc["diataxis"] == "how-to"
        assert doc["meta"]["title"] == "Operations Guide"
        assert doc["meta"]["header"] == SAMPLE_HEADER
        assert len(doc["sections"]) == 2
        assert doc["sections"][0]["slug"] == "monitoring-alerting"
        assert doc["sections"][1]["slug"] == "deployment"
        assert "ETL run log" in doc["sections"][0]["body"]
        assert "CI/CD" in doc["sections"][1]["body"]
        # Flat sections have empty children
        assert doc["sections"][0]["children"] == []
        assert doc["sections"][1]["children"] == []

    def test_round_trip_nested_2_levels(self):
        """2-level nesting preserves children structure."""
        doc = _round_trip(NESTED_SECTIONS_2)

        assert len(doc["sections"]) == 2
        parent = doc["sections"][0]
        assert parent["slug"] == "monitoring-alerting"
        assert "Intro to monitoring" in parent["body"]
        assert len(parent["children"]) == 2

        child1 = parent["children"][0]
        assert child1["slug"] == "etl-run-logging"
        assert "Logs all pipeline runs" in child1["body"]
        assert child1["children"] == []

        child2 = parent["children"][1]
        assert child2["slug"] == "alert-routing"
        assert "Routes alerts" in child2["body"]
        assert child2["children"] == []

        # Second top-level is a leaf
        assert doc["sections"][1]["slug"] == "deployment"
        assert doc["sections"][1]["children"] == []

    def test_round_trip_nested_3_levels(self):
        """3-level nesting preserves grandchild structure."""
        doc = _round_trip(NESTED_SECTIONS_3)

        parent = doc["sections"][0]
        assert parent["slug"] == "monitoring-alerting"

        child = parent["children"][0]
        assert child["slug"] == "etl-run-logging"

        grandchild = child["children"][0]
        assert grandchild["slug"] == "artifact-format"
        assert "JSON artifact" in grandchild["body"]
        assert grandchild["children"] == []

    def test_body_isolation(self):
        """Each section body contains only its own prose, not child content."""
        doc = _round_trip(NESTED_SECTIONS_2)

        parent = doc["sections"][0]
        # Parent body has intro text but NOT child content
        assert "Intro to monitoring" in parent["body"]
        assert "Logs all pipeline runs" not in parent["body"]
        assert "Routes alerts" not in parent["body"]

    def test_children_default_empty_when_absent(self):
        """Sections without 'children' key default to empty list."""
        sections_no_children = [
            {"slug": "overview", "body": "## Overview\n\nText."},
        ]
        doc = _round_trip(sections_no_children)
        assert doc["sections"][0]["children"] == []

    def test_title_extracted_from_header(self):
        """Title is extracted from header if not explicitly provided."""
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, [])
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            assert doc["meta"]["title"] == "Operations Guide"
        finally:
            os.unlink(path)

    def test_empty_sections(self):
        """Document with no sections is valid."""
        doc = _round_trip([], audience="end-users", diataxis="tutorial",
                          header="# Guide", title="Guide")
        assert doc["sections"] == []
        assert doc["audience"] == "end-users"

    def test_empty_refs(self):
        """Sections start with empty refs at all levels."""
        doc = _round_trip(NESTED_SECTIONS_2)
        for section in doc["sections"]:
            assert section["refs"] == []
            for child in section["children"]:
                assert child["refs"] == []


# ===================================================================
# walk_sections
# ===================================================================

class TestWalkSections:
    """walk_sections yields (path, section_dict) in depth-first order."""

    def test_empty_list(self):
        """walk_sections on empty list yields nothing."""
        result = list(walk_sections([]))
        assert result == []

    def test_flat_sections(self):
        """Flat sections yield bare slugs as paths."""
        doc = _round_trip(FLAT_SECTIONS)
        result = list(walk_sections(doc["sections"]))
        assert len(result) == 2
        assert result[0][0] == "monitoring-alerting"
        assert result[0][1]["slug"] == "monitoring-alerting"
        assert result[1][0] == "deployment"
        assert result[1][1]["slug"] == "deployment"

    def test_nested_sections_depth_first(self):
        """Nested sections yield depth-first paths with slash separators."""
        doc = _round_trip(NESTED_SECTIONS_2)
        result = list(walk_sections(doc["sections"]))

        paths = [p for p, _ in result]
        assert paths == [
            "monitoring-alerting",
            "monitoring-alerting/etl-run-logging",
            "monitoring-alerting/alert-routing",
            "deployment",
        ]

    def test_3_level_paths(self):
        """3-level nesting produces grandchild paths."""
        doc = _round_trip(NESTED_SECTIONS_3)
        result = list(walk_sections(doc["sections"]))

        paths = [p for p, _ in result]
        assert paths == [
            "monitoring-alerting",
            "monitoring-alerting/etl-run-logging",
            "monitoring-alerting/etl-run-logging/artifact-format",
        ]

    def test_yields_section_dicts(self):
        """Each yielded item is a section dict with slug, body, refs, children."""
        doc = _round_trip(NESTED_SECTIONS_2)
        for path, section in walk_sections(doc["sections"]):
            assert "slug" in section
            assert "body" in section
            assert "refs" in section
            assert "children" in section


# ===================================================================
# get_section_paths (renamed from get_section_slugs)
# ===================================================================

class TestGetSectionPaths:
    """get_section_paths returns slash-separated paths at all depths."""

    def test_flat_sections_returns_bare_slugs(self):
        """Top-level sections return bare slugs (backward compat)."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        paths = get_section_paths(tree)
        assert paths == ["monitoring-alerting", "deployment"]

    def test_nested_sections_returns_all_paths(self):
        """Returns paths for nested sections too."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        paths = get_section_paths(tree)
        assert paths == [
            "monitoring-alerting",
            "monitoring-alerting/etl-run-logging",
            "monitoring-alerting/alert-routing",
            "deployment",
        ]

    def test_3_level_paths(self):
        """Returns grandchild paths."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_3)
        paths = get_section_paths(tree)
        assert paths == [
            "monitoring-alerting",
            "monitoring-alerting/etl-run-logging",
            "monitoring-alerting/etl-run-logging/artifact-format",
        ]

    def test_empty_document(self):
        tree = build_xml_doc("devops", "how-to", "# Title", [])
        assert get_section_paths(tree) == []


# ===================================================================
# get_section_slugs backward compatibility
# ===================================================================

class TestGetSectionSlugs:
    """get_section_slugs still works as backward-compat alias."""

    def test_returns_slugs_in_order(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        assert get_section_slugs(tree) == ["monitoring-alerting", "deployment"]

    def test_empty_document(self):
        tree = build_xml_doc("devops", "how-to", "# Title", [])
        assert get_section_slugs(tree) == []


# ===================================================================
# _find_section_by_path (tested indirectly through public API)
# ===================================================================

class TestFindSectionByPath:
    """_find_section_by_path resolves paths level by level."""

    def test_single_segment_finds_top_level(self):
        """Bare slug (single-segment path) finds top-level section."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        # update_section_body uses _find_section which wraps _find_section_by_path
        update_section_body(tree, "monitoring-alerting", "Updated parent body")

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            assert doc["sections"][0]["body"] == "Updated parent body"
        finally:
            os.unlink(path)

    def test_multi_segment_finds_nested(self):
        """Slash-separated path finds nested section."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        update_section_body(tree, "monitoring-alerting/etl-run-logging", "Updated child body")

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            child = doc["sections"][0]["children"][0]
            assert child["body"] == "Updated child body"
        finally:
            os.unlink(path)

    def test_3_level_path(self):
        """3-segment path resolves to grandchild."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_3)
        update_section_body(
            tree,
            "monitoring-alerting/etl-run-logging/artifact-format",
            "Updated grandchild body",
        )

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            grandchild = doc["sections"][0]["children"][0]["children"][0]
            assert grandchild["body"] == "Updated grandchild body"
        finally:
            os.unlink(path)

    def test_missing_path_raises(self):
        """Missing path raises ValueError."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        with pytest.raises(ValueError, match="nonexistent"):
            update_section_body(tree, "nonexistent", "body")

    def test_partial_path_raises(self):
        """Path where intermediate segment is missing raises ValueError."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        with pytest.raises(ValueError, match="monitoring-alerting/nonexistent"):
            update_section_body(tree, "monitoring-alerting/nonexistent", "body")


# ===================================================================
# update_section_body with paths
# ===================================================================

class TestUpdateSectionBody:
    """update_section_body accepts slash-separated paths."""

    def test_body_updated_flat(self):
        """Update top-level section by bare slug."""
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, FLAT_SECTIONS)
        new_body = "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nUpdated content here."
        update_section_body(tree, "monitoring-alerting", new_body)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            assert "Updated content here." in doc["sections"][0]["body"]
            assert "CI/CD" in doc["sections"][1]["body"]
        finally:
            os.unlink(path)

    def test_body_updated_nested(self):
        """Update nested section by slash-separated path."""
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, NESTED_SECTIONS_2)
        update_section_body(tree, "monitoring-alerting/alert-routing", "New alert routing body")

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            child = doc["sections"][0]["children"][1]
            assert child["body"] == "New alert routing body"
            # Parent unchanged
            assert "Intro to monitoring" in doc["sections"][0]["body"]
        finally:
            os.unlink(path)

    def test_missing_path_raises(self):
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, FLAT_SECTIONS)
        with pytest.raises(ValueError, match="nonexistent"):
            update_section_body(tree, "nonexistent", "body")


# ===================================================================
# last-updated stamping
# ===================================================================

class TestLastUpdatedStamping:
    """Every section-mutating helper must stamp today's date into the
    `last-updated` attribute, so staleness-check has an accurate anchor."""

    def _reparse(self, tree):
        """Serialize then re-parse to ensure attributes round-trip via XML."""
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            return parse_xml_doc(path)
        finally:
            os.unlink(path)

    def _today(self):
        from datetime import date
        return date.today().isoformat()

    def test_build_stamps_each_section(self):
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, FLAT_SECTIONS)
        doc = self._reparse(tree)
        today = self._today()
        for section in doc["sections"]:
            assert section["last_updated"] == today

    def test_update_body_stamps_today(self):
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, FLAT_SECTIONS)
        # Pre-seed an older date to prove the stamp overwrites
        from lib.xml_doc import stamp_section_updated
        stamp_section_updated(tree, "monitoring-alerting", "2020-01-01")
        update_section_body(tree, "monitoring-alerting", "fresh body")

        doc = self._reparse(tree)
        assert doc["sections"][0]["last_updated"] == self._today()

    def test_update_refs_stamps_today(self):
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, FLAT_SECTIONS)
        from lib.xml_doc import stamp_section_updated
        stamp_section_updated(tree, "monitoring-alerting", "2020-01-01")
        update_section_refs(
            tree,
            "monitoring-alerting",
            [{"type": "flow", "name": "ingest-data"}],
        )

        doc = self._reparse(tree)
        assert doc["sections"][0]["last_updated"] == self._today()

    def test_add_section_stamps_today(self):
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, FLAT_SECTIONS)
        add_section(tree, "brand-new", "## Brand New\nFresh section")

        doc = self._reparse(tree)
        new_section = next(
            s for s in doc["sections"] if s["slug"] == "brand-new"
        )
        assert new_section["last_updated"] == self._today()

    def test_explicit_date_preserved(self):
        """Passing date_str to stamp_section_updated uses it verbatim
        (needed for test fixtures reproducing known dates)."""
        from lib.xml_doc import stamp_section_updated
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, FLAT_SECTIONS)
        stamp_section_updated(tree, "monitoring-alerting", "2025-06-15")

        doc = self._reparse(tree)
        assert doc["sections"][0]["last_updated"] == "2025-06-15"


# ===================================================================
# update_section_refs with paths
# ===================================================================

class TestUpdateSectionRefs:
    """update_section_refs accepts slash-separated paths."""

    def test_refs_on_nested_section(self):
        """Refs set on a nested child section via path."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        flat_refs = [
            {"type": "flow", "name": "ingest-data"},
        ]
        update_section_refs(tree, "monitoring-alerting/etl-run-logging", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            child = doc["sections"][0]["children"][0]
            assert len(child["refs"]) == 1
            assert child["refs"][0] == {"type": "flow", "name": "ingest-data"}
            # Parent refs unchanged (empty)
            assert doc["sections"][0]["refs"] == []
        finally:
            os.unlink(path)

    def test_refs_per_section_not_inherited(self):
        """Parent and child can have independent refs."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "flow", "name": "parent-flow"},
        ])
        update_section_refs(tree, "monitoring-alerting/etl-run-logging", [
            {"type": "flow", "name": "child-flow"},
        ])

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            parent = doc["sections"][0]
            child = parent["children"][0]
            assert parent["refs"][0]["name"] == "parent-flow"
            assert child["refs"][0]["name"] == "child-flow"
        finally:
            os.unlink(path)

    def test_db_refs(self):
        """Round-trip: 2 column refs → 5 total (1 db + 1 schema + 1 table + 2 columns)."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "db", "db": "road_runner_db", "schema": "road_runner",
             "table": "etl_runs", "column": "flow_name"},
            {"type": "db", "db": "road_runner_db", "schema": "road_runner",
             "table": "etl_runs", "column": "status"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            # db-level, schema-level, table-level, 2 column-level = 5
            assert len(refs) == 5
            assert refs[0] == {"type": "db", "db": "road_runner_db"}
            assert refs[1] == {"type": "db", "db": "road_runner_db", "schema": "road_runner"}
            assert refs[2] == {"type": "db", "db": "road_runner_db", "schema": "road_runner",
                               "table": "etl_runs"}
            assert refs[3] == {"type": "db", "db": "road_runner_db", "schema": "road_runner",
                               "table": "etl_runs", "column": "flow_name"}
            assert refs[4] == {"type": "db", "db": "road_runner_db", "schema": "road_runner",
                               "table": "etl_runs", "column": "status"}
        finally:
            os.unlink(path)

    def test_db_refs_build_writes_db_name(self):
        """_build_db_xml writes name= attribute on <db> element."""
        from lxml import etree
        from lib.xml_doc import _build_db_xml
        refs_el = etree.Element("refs")
        _build_db_xml(refs_el, [
            {"type": "db", "db": "mydb", "schema": "public", "table": "users"},
        ])
        db_el = refs_el.find("db")
        assert db_el is not None
        assert db_el.get("name") == "mydb"

    def test_db_refs_parse_all_levels(self):
        """_parse_db_refs emits refs at every level (db, schema, table, column)."""
        from lxml import etree
        from lib.xml_doc import _parse_db_refs
        xml = '<db name="mydb"><schema name="public"><table name="users"><column>id</column></table></schema></db>'
        db_el = etree.fromstring(xml)
        refs = _parse_db_refs(db_el)
        assert len(refs) == 4
        assert refs[0] == {"type": "db", "db": "mydb"}
        assert refs[1] == {"type": "db", "db": "mydb", "schema": "public"}
        assert refs[2] == {"type": "db", "db": "mydb", "schema": "public", "table": "users"}
        assert refs[3] == {"type": "db", "db": "mydb", "schema": "public",
                           "table": "users", "column": "id"}

    def test_db_refs_full_hierarchy_round_trip(self):
        """Full hierarchy in → all levels parsed back → rebuild matches."""
        from lxml import etree
        from lib.xml_doc import _build_db_xml, _parse_db_refs
        # Build XML from full hierarchy refs
        input_refs = [
            {"type": "db", "db": "testdb"},
            {"type": "db", "db": "testdb", "schema": "main"},
            {"type": "db", "db": "testdb", "schema": "main", "table": "orders"},
            {"type": "db", "db": "testdb", "schema": "main", "table": "orders",
             "column": "total"},
        ]
        refs_el = etree.Element("refs")
        _build_db_xml(refs_el, input_refs)

        # Parse back
        db_el = refs_el.find("db")
        parsed = _parse_db_refs(db_el)
        assert parsed == input_refs

        # Rebuild and compare XML
        refs_el2 = etree.Element("refs")
        _build_db_xml(refs_el2, parsed)
        xml1 = etree.tostring(refs_el, encoding="unicode", pretty_print=True)
        xml2 = etree.tostring(refs_el2, encoding="unicode", pretty_print=True)
        assert xml1 == xml2

    def test_code_refs_class_and_function(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "code", "kind": "class", "name": "EtlRun",
             "module": "src/road_runner/db/models.py", "attr": "status"},
            {"type": "code", "kind": "function", "name": "compute_finance_metrics",
             "module": "src/road_runner/flows/compute.py", "param": "recompute_stale"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            class_ref = refs[0]
            assert class_ref["type"] == "code"
            assert class_ref["kind"] == "class"
            assert class_ref["name"] == "EtlRun"
            assert class_ref["module"] == "src/road_runner/db/models.py"
            assert class_ref["attr"] == "status"
            func_ref = refs[1]
            assert func_ref["type"] == "code"
            assert func_ref["kind"] == "function"
            assert func_ref["name"] == "compute_finance_metrics"
            assert func_ref["module"] == "src/road_runner/flows/compute.py"
            assert func_ref["param"] == "recompute_stale"
        finally:
            os.unlink(path)

    def test_code_refs_class_module_disambiguation(self):
        """Same class name in different modules produces two distinct refs."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "code", "kind": "class", "name": "Settings",
             "module": "src/road_runner/config.py"},
            {"type": "code", "kind": "class", "name": "Settings",
             "module": "src/other_app/config.py"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            modules = sorted(r["module"] for r in refs)
            assert modules == [
                "src/other_app/config.py",
                "src/road_runner/config.py",
            ]
            assert all(r["name"] == "Settings" for r in refs)
            assert all(r["kind"] == "class" for r in refs)
        finally:
            os.unlink(path)

    def test_code_refs_class_without_module(self):
        """Class refs without module continue to round-trip unchanged."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "code", "kind": "class", "name": "Run"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 1
            assert refs[0]["name"] == "Run"
            assert refs[0]["kind"] == "class"
            assert "module" not in refs[0]
        finally:
            os.unlink(path)

    def test_code_refs_variable(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "code", "kind": "variable", "name": "FMP_QUARTERLY_ENDPOINTS",
             "module": "src/road_runner/fmp/endpoints.py"},
            {"type": "code", "kind": "variable", "name": "DEFAULT_TIMEOUT"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            assert refs[0]["module"] == "src/road_runner/fmp/endpoints.py"
            assert "module" not in refs[1]
        finally:
            os.unlink(path)

    def test_flow_env_config_refs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "flow", "name": "ingest-quarterly-finance-data"},
            {"type": "env", "name": "WORKER_CONCURRENCY"},
            {"type": "config", "path": "config/field-mapping.yaml"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 3
            assert refs[0] == {"type": "flow", "name": "ingest-quarterly-finance-data"}
            assert refs[1] == {"type": "env", "name": "WORKER_CONCURRENCY"}
            assert refs[2] == {"type": "config", "path": "config/field-mapping.yaml"}
        finally:
            os.unlink(path)

    def test_enum_refs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "enum", "class": "EtlRun", "field": "status", "value": "completed"},
            {"type": "enum", "class": "EtlRun", "field": "status", "value": "failed"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            assert refs[0] == {"type": "enum", "class": "EtlRun", "field": "status", "value": "completed"}
            assert refs[1] == {"type": "enum", "class": "EtlRun", "field": "status", "value": "failed"}
        finally:
            os.unlink(path)

    def test_mixed_refs_all_types(self):
        """All nine ref types in one update."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "db", "schema": "rr", "table": "runs", "column": "id"},
            {"type": "code", "kind": "class", "name": "Run"},
            {"type": "flow", "name": "ingest"},
            {"type": "env", "name": "PORT"},
            {"type": "config", "path": "config.yaml"},
            {"type": "enum", "class": "Run", "field": "status", "value": "ok"},
            {"type": "dep", "name": "tenacity"},
            {"type": "literal", "name": "fmp-api"},
            {"type": "ext", "name": "pg_dump"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            types = [r["type"] for r in refs]
            for t in ["db", "code", "flow", "env", "config", "enum", "dep", "literal", "ext"]:
                assert t in types
        finally:
            os.unlink(path)

    def test_dep_refs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "dep", "name": "tenacity"},
            {"type": "dep", "name": "edgartools"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            assert refs[0] == {"type": "dep", "name": "tenacity"}
            assert refs[1] == {"type": "dep", "name": "edgartools"}
        finally:
            os.unlink(path)

    def test_literal_refs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "literal", "name": "fmp-api"},
            {"type": "literal", "name": "finance-data-pool"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            assert refs[0] == {"type": "literal", "name": "fmp-api"}
            assert refs[1] == {"type": "literal", "name": "finance-data-pool"}
        finally:
            os.unlink(path)

    def test_ext_refs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        flat_refs = [
            {"type": "ext", "name": "pg_dump"},
            {"type": "ext", "name": "VACUUM"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            assert refs[0] == {"type": "ext", "name": "pg_dump"}
            assert refs[1] == {"type": "ext", "name": "VACUUM"}
        finally:
            os.unlink(path)

    def test_replace_existing_refs(self):
        """Updating refs replaces previous refs entirely."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "flow", "name": "old-flow"},
        ])
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "flow", "name": "new-flow"},
        ])

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 1
            assert refs[0]["name"] == "new-flow"
        finally:
            os.unlink(path)

    def test_missing_path_raises(self):
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        with pytest.raises(ValueError, match="nonexistent"):
            update_section_refs(tree, "nonexistent", [])


# ===================================================================
# add_section with optional parent_path
# ===================================================================

class TestAddSection:
    """add_section supports parent_path and sibling slug uniqueness."""

    def test_add_to_root_without_parent(self):
        """Without parent_path, section appends to root (backward compat)."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        add_section(tree, "new-section", "## New Section\n\nNew body.")

        paths = get_section_paths(tree)
        assert "new-section" in paths

    def test_add_with_parent_path(self):
        """With parent_path, section appends as child of parent."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        add_section(tree, "new-child", "### New Child\n\nChild body.",
                    parent_path="monitoring-alerting")

        paths = get_section_paths(tree)
        assert "monitoring-alerting/new-child" in paths

    def test_missing_parent_raises(self):
        """Nonexistent parent_path raises ValueError."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        with pytest.raises(ValueError, match="nonexistent"):
            add_section(tree, "child", "body", parent_path="nonexistent")

    def test_duplicate_sibling_slug_raises(self):
        """Adding a section with a slug that already exists as a sibling raises."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        with pytest.raises(ValueError, match="etl-run-logging"):
            add_section(tree, "etl-run-logging", "duplicate body",
                        parent_path="monitoring-alerting")

    def test_same_slug_different_parents_ok(self):
        """Same slug under different parents is allowed (sibling uniqueness)."""
        sections = [
            {"slug": "parent-a", "body": "## Parent A", "children": []},
            {"slug": "parent-b", "body": "## Parent B", "children": []},
        ]
        tree = build_xml_doc("devops", "how-to", "# Title", sections)
        add_section(tree, "prereqs", "### Prerequisites\n\nA prereqs.",
                    parent_path="parent-a")
        add_section(tree, "prereqs", "### Prerequisites\n\nB prereqs.",
                    parent_path="parent-b")

        paths = get_section_paths(tree)
        assert "parent-a/prereqs" in paths
        assert "parent-b/prereqs" in paths

    def test_duplicate_root_slug_raises(self):
        """Adding a root section with duplicate slug raises."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        with pytest.raises(ValueError, match="monitoring-alerting"):
            add_section(tree, "monitoring-alerting", "duplicate body")


# ===================================================================
# Serialize
# ===================================================================

class TestSerialize:
    """serialize_xml_doc writes valid XML."""

    def test_creates_parent_dirs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", [])
        with tempfile.TemporaryDirectory() as td:
            path = os.path.join(td, "nested", "dir", "doc.xml")
            serialize_xml_doc(tree, path)
            assert os.path.isfile(path)
            doc = parse_xml_doc(path)
            assert doc["audience"] == "devops"

    def test_atomic_write_no_leftover_tmp(self):
        """No .tmp file left after successful write."""
        tree = build_xml_doc("devops", "how-to", "# Title", [])
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            assert not os.path.exists(path + ".tmp")
        finally:
            os.unlink(path)


# ===================================================================
# Round-trip fidelity (parameterized at 1, 2, 3 levels)
# ===================================================================

class TestRoundTrip:
    """Parameterized round-trip tests: build -> serialize -> parse."""

    @pytest.mark.parametrize("sections,expected_paths", [
        # 1 level (flat)
        (
            FLAT_SECTIONS,
            ["monitoring-alerting", "deployment"],
        ),
        # 2 levels
        (
            NESTED_SECTIONS_2,
            [
                "monitoring-alerting",
                "monitoring-alerting/etl-run-logging",
                "monitoring-alerting/alert-routing",
                "deployment",
            ],
        ),
        # 3 levels
        (
            NESTED_SECTIONS_3,
            [
                "monitoring-alerting",
                "monitoring-alerting/etl-run-logging",
                "monitoring-alerting/etl-run-logging/artifact-format",
            ],
        ),
    ], ids=["1-level", "2-level", "3-level"])
    def test_paths_preserved(self, sections, expected_paths):
        """All section paths survive round-trip."""
        doc = _round_trip(sections)
        actual_paths = [p for p, _ in walk_sections(doc["sections"])]
        assert actual_paths == expected_paths

    @pytest.mark.parametrize("sections", [
        FLAT_SECTIONS,
        NESTED_SECTIONS_2,
        NESTED_SECTIONS_3,
    ], ids=["1-level", "2-level", "3-level"])
    def test_slugs_preserved(self, sections):
        """All slugs survive round-trip."""
        doc = _round_trip(sections)
        for path, section in walk_sections(doc["sections"]):
            expected_slug = path.rsplit("/", 1)[-1]
            assert section["slug"] == expected_slug

    @pytest.mark.parametrize("sections", [
        FLAT_SECTIONS,
        NESTED_SECTIONS_2,
        NESTED_SECTIONS_3,
    ], ids=["1-level", "2-level", "3-level"])
    def test_bodies_preserved(self, sections):
        """All bodies survive round-trip (non-empty)."""
        doc = _round_trip(sections)
        for _, section in walk_sections(doc["sections"]):
            assert len(section["body"]) > 0

    @pytest.mark.parametrize("sections", [
        FLAT_SECTIONS,
        NESTED_SECTIONS_2,
        NESTED_SECTIONS_3,
    ], ids=["1-level", "2-level", "3-level"])
    def test_refs_preserved(self, sections):
        """All refs survive round-trip (initially empty)."""
        doc = _round_trip(sections)
        for _, section in walk_sections(doc["sections"]):
            assert section["refs"] == []

    @pytest.mark.parametrize("sections", [
        FLAT_SECTIONS,
        NESTED_SECTIONS_2,
        NESTED_SECTIONS_3,
    ], ids=["1-level", "2-level", "3-level"])
    def test_children_key_present(self, sections):
        """All sections have children key."""
        doc = _round_trip(sections)
        for _, section in walk_sections(doc["sections"]):
            assert "children" in section

    def test_refs_round_trip_with_nested_refs(self):
        """Refs on nested sections survive round-trip."""
        tree = build_xml_doc("devops", "how-to", "# Title", NESTED_SECTIONS_2)
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "flow", "name": "parent-flow"},
        ])
        update_section_refs(tree, "monitoring-alerting/etl-run-logging", [
            {"type": "env", "name": "LOG_LEVEL"},
        ])

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            parent = doc["sections"][0]
            child = parent["children"][0]
            assert parent["refs"][0] == {"type": "flow", "name": "parent-flow"}
            assert child["refs"][0] == {"type": "env", "name": "LOG_LEVEL"}
        finally:
            os.unlink(path)


# ===================================================================
# Malformed ref XML round-trip
# ===================================================================

class TestMalformedRefXml:
    """Malformed refs survive XML build -> serialize -> parse round-trip."""

    def test_malformed_ref_round_trip(self):
        """A malformed ref is serialized and parsed back correctly."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "malformed", "original_type": "dep", "name": ""},
        ])
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 1
            assert refs[0]["type"] == "malformed"
            assert refs[0]["original_type"] == "dep"
            assert refs[0]["name"] == ""
        finally:
            os.unlink(path)

    def test_malformed_ref_preserves_extra_fields(self):
        """Extra fields on malformed ref survive round-trip."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "malformed", "original_type": "db", "schema": "", "table": "runs", "column": "id"},
        ])
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 1
            r = refs[0]
            assert r["type"] == "malformed"
            assert r["original_type"] == "db"
            assert r["schema"] == ""
            assert r["table"] == "runs"
            assert r["column"] == "id"
        finally:
            os.unlink(path)

    def test_malformed_mixed_with_normal_refs(self):
        """Malformed refs coexist with normal refs."""
        tree = build_xml_doc("devops", "how-to", "# Title", FLAT_SECTIONS)
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "dep", "name": "tenacity"},
            {"type": "malformed", "original_type": "dep", "name": ""},
            {"type": "ext", "name": "pg_dump"},
        ])
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 3
            types = [r["type"] for r in refs]
            assert types == ["dep", "ext", "malformed"]
        finally:
            os.unlink(path)
