"""Tests for assemble-markdown.py -- XML to markdown assembly.

Covers assembly from XML, round-trip with sync-edits-to-xml.py, and CLI.
"""

import os
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from lib.xml_doc import build_xml_doc, serialize_xml_doc

SCRIPTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ASSEMBLE_SCRIPT = os.path.join(SCRIPTS_DIR, "assemble-markdown.py")

SAMPLE_HEADER = """<!-- This file is auto-generated by /mg:auto-doc -->
<!-- DIATAXIS: how-to -->
<!-- AUDIENCE: devops -->

# Operations Guide"""

SAMPLE_SECTIONS = [
    {
        "slug": "monitoring-alerting",
        "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nThe ETL run log tracks all pipeline executions.",
    },
    {
        "slug": "deployment",
        "body": "<!-- section: deployment -->\n## Deployment\n\nDeploy via CI/CD pipeline.",
    },
]


class TestAssembleMarkdown:
    """assemble-markdown.py produces correct markdown from XML."""

    def _build_xml(self, td):
        """Build a sample XML file, return its path."""
        xml_path = os.path.join(td, "doc.xml")
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, SAMPLE_SECTIONS,
                             title="Operations Guide")
        serialize_xml_doc(tree, xml_path)
        return xml_path

    def test_assembly_content(self):
        """Assembled .md has header + sections in order."""
        with tempfile.TemporaryDirectory() as td:
            xml_path = self._build_xml(td)
            md_path = os.path.join(td, "out.md")

            result = subprocess.run(
                [sys.executable, ASSEMBLE_SCRIPT,
                 "--xml-file", xml_path, "--output", md_path],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr

            with open(md_path, "r") as f:
                content = f.read()

            # Header present
            assert "<!-- AUDIENCE: devops -->" in content
            assert "# Operations Guide" in content
            # Section markers present
            assert "<!-- section: monitoring-alerting -->" in content
            assert "<!-- section: deployment -->" in content
            # Section content present
            assert "ETL run log" in content
            assert "CI/CD" in content
            # Sections in correct order
            mon_pos = content.index("monitoring-alerting")
            dep_pos = content.index("deployment")
            assert mon_pos < dep_pos

    def test_assembly_ends_with_newline(self):
        """Assembled markdown ends with exactly one newline."""
        with tempfile.TemporaryDirectory() as td:
            xml_path = self._build_xml(td)
            md_path = os.path.join(td, "out.md")

            subprocess.run(
                [sys.executable, ASSEMBLE_SCRIPT,
                 "--xml-file", xml_path, "--output", md_path],
                capture_output=True, text=True,
            )
            with open(md_path, "r") as f:
                content = f.read()
            assert content.endswith("\n")
            assert not content.endswith("\n\n")

    def test_missing_xml_file_exits_1(self):
        """Exit 1 when XML file doesn't exist."""
        result = subprocess.run(
            [sys.executable, ASSEMBLE_SCRIPT,
             "--xml-file", "/nonexistent/path.xml", "--output", "/tmp/out.md"],
            capture_output=True, text=True,
        )
        assert result.returncode == 1
        assert "not found" in result.stderr

    def test_empty_document(self):
        """Document with no sections produces just the header."""
        with tempfile.TemporaryDirectory() as td:
            xml_path = os.path.join(td, "empty.xml")
            tree = build_xml_doc("devops", "how-to", "# Just a Title", [])
            serialize_xml_doc(tree, xml_path)
            md_path = os.path.join(td, "out.md")

            subprocess.run(
                [sys.executable, ASSEMBLE_SCRIPT,
                 "--xml-file", xml_path, "--output", md_path],
                capture_output=True, text=True,
            )
            with open(md_path, "r") as f:
                content = f.read()
            assert content.strip() == "# Just a Title"
