"""Tests for sync-edits-to-xml.py -- markdown to XML sync.

Covers: basic sync, no-change detection, partial edits, and the full
round-trip: build XML → assemble .md → edit .md → sync → reassemble → identical.
"""

import os
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from lib.xml_doc import build_xml_doc, parse_xml_doc, serialize_xml_doc

SCRIPTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ASSEMBLE_SCRIPT = os.path.join(SCRIPTS_DIR, "assemble-markdown.py")
SYNC_SCRIPT = os.path.join(SCRIPTS_DIR, "sync-edits-to-xml.py")

SAMPLE_HEADER = """<!-- This file is auto-generated by /mg:auto-doc -->
<!-- DIATAXIS: how-to -->
<!-- AUDIENCE: devops -->

# Operations Guide"""

SAMPLE_SECTIONS = [
    {
        "slug": "monitoring-alerting",
        "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nThe ETL run log tracks all pipeline executions.",
    },
    {
        "slug": "deployment",
        "body": "<!-- section: deployment -->\n## Deployment\n\nDeploy via CI/CD pipeline.",
    },
]


def _build_and_assemble(td):
    """Build XML, assemble .md, return (xml_path, md_path)."""
    xml_path = os.path.join(td, "doc.xml")
    md_path = os.path.join(td, "doc.md")

    tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, SAMPLE_SECTIONS,
                         title="Operations Guide")
    serialize_xml_doc(tree, xml_path)

    result = subprocess.run(
        [sys.executable, ASSEMBLE_SCRIPT,
         "--xml-file", xml_path, "--output", md_path],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stderr
    return xml_path, md_path


class TestSyncEdits:
    """sync-edits-to-xml.py syncs markdown changes back to XML."""

    def test_no_change_sync(self):
        """Syncing unmodified .md produces zero changed slugs."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            assert changed == []

    def test_single_section_edit(self):
        """Editing one section syncs only that section."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            # Edit the monitoring section
            with open(md_path, "r") as f:
                content = f.read()
            content = content.replace(
                "The ETL run log tracks all pipeline executions.",
                "The ETL run log tracks all pipeline executions in real-time."
            )
            with open(md_path, "w") as f:
                f.write(content)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            assert changed == ["monitoring-alerting"]

            # Verify XML was updated
            doc = parse_xml_doc(xml_path)
            assert "real-time" in doc["sections"][0]["body"]
            # Other section unchanged
            assert "CI/CD" in doc["sections"][1]["body"]

    def test_multiple_section_edits(self):
        """Editing two sections syncs both."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            with open(md_path, "r") as f:
                content = f.read()
            content = content.replace("ETL run log", "ETL execution log")
            content = content.replace("CI/CD pipeline", "GitHub Actions pipeline")
            with open(md_path, "w") as f:
                f.write(content)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            assert set(changed) == {"monitoring-alerting", "deployment"}

    def test_full_round_trip(self):
        """Build XML → assemble .md → edit .md → sync → reassemble → content matches."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            # Edit the markdown
            with open(md_path, "r") as f:
                original = f.read()
            edited = original.replace("ETL run log", "ETL execution log")
            with open(md_path, "w") as f:
                f.write(edited)

            # Sync edits back to XML
            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr

            # Reassemble markdown from synced XML
            md_path2 = os.path.join(td, "reassembled.md")
            result = subprocess.run(
                [sys.executable, ASSEMBLE_SCRIPT,
                 "--xml-file", xml_path, "--output", md_path2],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr

            with open(md_path2, "r") as f:
                reassembled = f.read()

            # Reassembled content should match the edited version
            assert reassembled == edited

    def test_idempotent_round_trip(self):
        """Unedited .md: assemble → sync → reassemble produces identical output."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            with open(md_path, "r") as f:
                original = f.read()

            # Sync (no changes)
            subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path],
                capture_output=True, text=True,
            )

            # Reassemble
            md_path2 = os.path.join(td, "reassembled.md")
            subprocess.run(
                [sys.executable, ASSEMBLE_SCRIPT,
                 "--xml-file", xml_path, "--output", md_path2],
                capture_output=True, text=True,
            )

            with open(md_path2, "r") as f:
                reassembled = f.read()
            assert reassembled == original

    def test_missing_md_exits_1(self):
        """Exit 1 when .md file doesn't exist."""
        with tempfile.TemporaryDirectory() as td:
            xml_path = os.path.join(td, "doc.xml")
            tree = build_xml_doc("devops", "how-to", "# Title", [])
            serialize_xml_doc(tree, xml_path)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", "/nonexistent/path.md", "--xml-file", xml_path],
                capture_output=True, text=True,
            )
            assert result.returncode == 1

    def test_missing_xml_exits_1(self):
        """Exit 1 when XML file doesn't exist."""
        with tempfile.TemporaryDirectory() as td:
            md_path = os.path.join(td, "doc.md")
            with open(md_path, "w") as f:
                f.write("# Hello\n")

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", "/nonexistent/path.xml"],
                capture_output=True, text=True,
            )
            assert result.returncode == 1

    def test_unknown_slug_in_md_ignored(self):
        """Sections in .md with slugs not in XML are silently ignored."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            # Append a new section to .md that isn't in XML
            with open(md_path, "a") as f:
                f.write("\n\n<!-- section: bonus-section -->\n## Bonus\n\nExtra content.\n")

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            # bonus-section is not in XML, so it's not synced (no error either)
            assert "bonus-section" not in changed
