"""Tests for sync-edits-to-xml.py -- markdown to XML sync.

Covers: basic sync, no-change detection, partial edits, and the full
round-trip: build XML → assemble .md → edit .md → sync → reassemble → identical.
Also covers: _infer_paths heading-level tree reconstruction and nested sync.
"""

import importlib.util
import os
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from lib.xml_doc import build_xml_doc, parse_xml_doc, serialize_xml_doc

SCRIPTS_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
ASSEMBLE_SCRIPT = os.path.join(SCRIPTS_DIR, "assemble-markdown.py")
SYNC_SCRIPT = os.path.join(SCRIPTS_DIR, "sync-edits-to-xml.py")

# Import sync module for direct function testing
_spec = importlib.util.spec_from_file_location("sync_edits_to_xml", SYNC_SCRIPT)
_mod = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(_mod)
_infer_paths = _mod._infer_paths
sync = _mod.sync

SAMPLE_HEADER = """<!-- This file is auto-generated by /mg:auto-doc -->
<!-- DIATAXIS: how-to -->
<!-- AUDIENCE: devops -->

# Operations Guide"""

SAMPLE_SECTIONS = [
    {
        "slug": "monitoring-alerting",
        "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nThe ETL run log tracks all pipeline executions.",
    },
    {
        "slug": "deployment",
        "body": "<!-- section: deployment -->\n## Deployment\n\nDeploy via CI/CD pipeline.",
    },
]


def _build_and_assemble(td):
    """Build XML, assemble .md, return (xml_path, md_path)."""
    xml_path = os.path.join(td, "doc.xml")
    md_path = os.path.join(td, "doc.md")

    tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, SAMPLE_SECTIONS,
                         title="Operations Guide")
    serialize_xml_doc(tree, xml_path)

    result = subprocess.run(
        [sys.executable, ASSEMBLE_SCRIPT,
         "--xml-file", xml_path, "--output", md_path],
        capture_output=True, text=True,
    )
    assert result.returncode == 0, result.stderr
    return xml_path, md_path


class TestSyncEdits:
    """sync-edits-to-xml.py syncs markdown changes back to XML."""

    def test_no_change_sync(self):
        """Syncing unmodified .md produces zero changed slugs."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            assert changed == []

    def test_single_section_edit(self):
        """Editing one section syncs only that section."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            # Edit the monitoring section
            with open(md_path, "r") as f:
                content = f.read()
            content = content.replace(
                "The ETL run log tracks all pipeline executions.",
                "The ETL run log tracks all pipeline executions in real-time."
            )
            with open(md_path, "w") as f:
                f.write(content)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            assert changed == ["monitoring-alerting"]

            # Verify XML was updated
            doc = parse_xml_doc(xml_path)
            assert "real-time" in doc["sections"][0]["body"]
            # Other section unchanged
            assert "CI/CD" in doc["sections"][1]["body"]

    def test_multiple_section_edits(self):
        """Editing two sections syncs both."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            with open(md_path, "r") as f:
                content = f.read()
            content = content.replace("ETL run log", "ETL execution log")
            content = content.replace("CI/CD pipeline", "GitHub Actions pipeline")
            with open(md_path, "w") as f:
                f.write(content)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            assert set(changed) == {"monitoring-alerting", "deployment"}

    def test_full_round_trip(self):
        """Build XML → assemble .md → edit .md → sync → reassemble → content matches."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            # Edit the markdown
            with open(md_path, "r") as f:
                original = f.read()
            edited = original.replace("ETL run log", "ETL execution log")
            with open(md_path, "w") as f:
                f.write(edited)

            # Sync edits back to XML
            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr

            # Reassemble markdown from synced XML
            md_path2 = os.path.join(td, "reassembled.md")
            result = subprocess.run(
                [sys.executable, ASSEMBLE_SCRIPT,
                 "--xml-file", xml_path, "--output", md_path2],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr

            with open(md_path2, "r") as f:
                reassembled = f.read()

            # Reassembled content should match the edited version
            assert reassembled == edited

    def test_idempotent_round_trip(self):
        """Unedited .md: assemble → sync → reassemble produces identical output."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            with open(md_path, "r") as f:
                original = f.read()

            # Sync (no changes)
            subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path],
                capture_output=True, text=True,
            )

            # Reassemble
            md_path2 = os.path.join(td, "reassembled.md")
            subprocess.run(
                [sys.executable, ASSEMBLE_SCRIPT,
                 "--xml-file", xml_path, "--output", md_path2],
                capture_output=True, text=True,
            )

            with open(md_path2, "r") as f:
                reassembled = f.read()
            assert reassembled == original

    def test_missing_md_exits_1(self):
        """Exit 1 when .md file doesn't exist."""
        with tempfile.TemporaryDirectory() as td:
            xml_path = os.path.join(td, "doc.xml")
            tree = build_xml_doc("devops", "how-to", "# Title", [])
            serialize_xml_doc(tree, xml_path)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", "/nonexistent/path.md", "--xml-file", xml_path],
                capture_output=True, text=True,
            )
            assert result.returncode == 1

    def test_missing_xml_exits_1(self):
        """Exit 1 when XML file doesn't exist."""
        with tempfile.TemporaryDirectory() as td:
            md_path = os.path.join(td, "doc.md")
            with open(md_path, "w") as f:
                f.write("# Hello\n")

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", "/nonexistent/path.xml"],
                capture_output=True, text=True,
            )
            assert result.returncode == 1

    def test_unknown_slug_in_md_ignored(self):
        """Sections in .md with slugs not in XML are silently ignored."""
        with tempfile.TemporaryDirectory() as td:
            xml_path, md_path = _build_and_assemble(td)

            # Append a new section to .md that isn't in XML
            with open(md_path, "a") as f:
                f.write("\n\n<!-- section: bonus-section -->\n## Bonus\n\nExtra content.\n")

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            # bonus-section is not in XML, so it's not synced (no error either)
            assert "bonus-section" not in changed


class TestInferPaths:
    """_infer_paths builds slash-separated paths from heading levels."""

    def test_single_top_level(self):
        """Single ## section produces bare slug as path."""
        sections = [("monitoring", "## Monitoring\n\nContent.")]
        result = _infer_paths(sections)
        assert len(result) == 1
        assert result[0] == ("monitoring", "monitoring", "## Monitoring\n\nContent.")

    def test_parent_child(self):
        """## followed by ### produces parent/child path."""
        sections = [
            ("monitoring-alerting", "## Monitoring & Alerting\n\nOverview."),
            ("etl-run-logging", "### ETL Run Logging\n\nLogs all runs."),
        ]
        result = _infer_paths(sections)
        assert result[0][0] == "monitoring-alerting"
        assert result[1][0] == "monitoring-alerting/etl-run-logging"

    def test_siblings_same_parent(self):
        """Two consecutive ### under same ## are siblings (same parent)."""
        sections = [
            ("monitoring-alerting", "## Monitoring & Alerting\n\nOverview."),
            ("etl-run-logging", "### ETL Run Logging\n\nLogs all runs."),
            ("alert-routing", "### Alert Routing\n\nRoutes alerts."),
        ]
        result = _infer_paths(sections)
        assert result[0][0] == "monitoring-alerting"
        assert result[1][0] == "monitoring-alerting/etl-run-logging"
        assert result[2][0] == "monitoring-alerting/alert-routing"

    def test_pop_back_to_top_level(self):
        """## after ### pops back to top level."""
        sections = [
            ("monitoring-alerting", "## Monitoring\n\nM."),
            ("etl-run-logging", "### ETL Logging\n\nE."),
            ("deployment", "## Deployment\n\nD."),
        ]
        result = _infer_paths(sections)
        assert result[0][0] == "monitoring-alerting"
        assert result[1][0] == "monitoring-alerting/etl-run-logging"
        assert result[2][0] == "deployment"

    def test_three_levels(self):
        """## -> ### -> #### produces three-level path."""
        sections = [
            ("monitoring", "## Monitoring\n\nM."),
            ("etl-logging", "### ETL Logging\n\nE."),
            ("artifact-format", "#### Artifact Format\n\nA."),
        ]
        result = _infer_paths(sections)
        assert result[0][0] == "monitoring"
        assert result[1][0] == "monitoring/etl-logging"
        assert result[2][0] == "monitoring/etl-logging/artifact-format"

    def test_heading_skip_treated_as_child(self):
        """#### directly under ## still produces child relationship."""
        sections = [
            ("monitoring", "## Monitoring\n\nM."),
            ("deep-child", "#### Deep Child\n\nD."),
        ]
        result = _infer_paths(sections)
        assert result[0][0] == "monitoring"
        assert result[1][0] == "monitoring/deep-child"

    def test_no_heading_defaults_to_top_level(self):
        """Section with no heading defaults to top-level (depth 2)."""
        sections = [
            ("no-heading", "Just some prose without a heading."),
        ]
        result = _infer_paths(sections)
        assert result[0][0] == "no-heading"

    def test_no_heading_after_child(self):
        """No-heading section after a ### is treated as ## (top-level)."""
        sections = [
            ("parent", "## Parent\n\nP."),
            ("child", "### Child\n\nC."),
            ("no-heading", "Just prose."),
        ]
        result = _infer_paths(sections)
        assert result[0][0] == "parent"
        assert result[1][0] == "parent/child"
        # no heading = depth 2 = same as ##, so pops back to top
        assert result[2][0] == "no-heading"


class TestNestedSync:
    """sync() on nested markdown updates correct sections in nested XML tree."""

    def test_sync_nested_section(self):
        """Syncing a nested section updates the correct child in XML."""
        with tempfile.TemporaryDirectory() as td:
            xml_path = os.path.join(td, "doc.xml")
            sections = [
                {
                    "slug": "monitoring-alerting",
                    "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nOverview.",
                    "children": [
                        {
                            "slug": "etl-run-logging",
                            "body": "<!-- section: etl-run-logging -->\n### ETL Run Logging\n\nOriginal child content.",
                        },
                    ],
                },
            ]
            tree = build_xml_doc("devops", "how-to", "# Ops Guide", sections,
                                 title="Ops Guide")
            serialize_xml_doc(tree, xml_path)

            # Build markdown with edited child section
            md_path = os.path.join(td, "doc.md")
            md_content = (
                "<!-- section: monitoring-alerting -->\n"
                "## Monitoring & Alerting\n\nOverview.\n\n"
                "<!-- section: etl-run-logging -->\n"
                "### ETL Run Logging\n\nUpdated child content."
            )
            with open(md_path, "w") as f:
                f.write(md_content)

            changed = sync(md_path, xml_path)
            assert "monitoring-alerting/etl-run-logging" in changed

            doc = parse_xml_doc(xml_path)
            child = doc["sections"][0]["children"][0]
            assert "Updated child content" in child["body"]

    def test_changed_only_outputs_paths(self):
        """--changed-only output includes slash-separated paths."""
        with tempfile.TemporaryDirectory() as td:
            xml_path = os.path.join(td, "doc.xml")
            sections = [
                {
                    "slug": "monitoring-alerting",
                    "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nOverview.",
                    "children": [
                        {
                            "slug": "etl-run-logging",
                            "body": "<!-- section: etl-run-logging -->\n### ETL Run Logging\n\nOriginal.",
                        },
                    ],
                },
            ]
            tree = build_xml_doc("devops", "how-to", "# Ops Guide", sections,
                                 title="Ops Guide")
            serialize_xml_doc(tree, xml_path)

            md_path = os.path.join(td, "doc.md")
            md_content = (
                "<!-- section: monitoring-alerting -->\n"
                "## Monitoring & Alerting\n\nOverview.\n\n"
                "<!-- section: etl-run-logging -->\n"
                "### ETL Run Logging\n\nChanged content."
            )
            with open(md_path, "w") as f:
                f.write(md_content)

            result = subprocess.run(
                [sys.executable, SYNC_SCRIPT,
                 "--md-file", md_path, "--xml-file", xml_path, "--changed-only"],
                capture_output=True, text=True,
            )
            assert result.returncode == 0, result.stderr
            import json
            changed = json.loads(result.stdout)
            assert "monitoring-alerting/etl-run-logging" in changed
