"""Tests for lib/xml_doc.py -- XML document model.

Covers build, parse, serialize, and mutation helpers. Verifies round-trip
fidelity: build → serialize → parse yields identical structure.
"""

import os
import sys
import tempfile

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
from lib.xml_doc import (
    build_xml_doc,
    get_section_slugs,
    parse_xml_doc,
    serialize_xml_doc,
    update_section_body,
    update_section_refs,
)

SAMPLE_HEADER = """<!-- This file is auto-generated by /mg:auto-doc -->
<!-- DIATAXIS: how-to -->
<!-- AUDIENCE: devops -->

# Operations Guide"""

SAMPLE_SECTIONS = [
    {
        "slug": "monitoring-alerting",
        "body": "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nThe ETL run log tracks all pipeline executions.",
    },
    {
        "slug": "deployment",
        "body": "<!-- section: deployment -->\n## Deployment\n\nDeploy via CI/CD pipeline.",
    },
]


class TestBuildAndParse:
    """build_xml_doc + parse_xml_doc round-trip."""

    def test_round_trip_structure(self):
        """Build → serialize → parse preserves audience, diataxis, header, sections."""
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, SAMPLE_SECTIONS,
                             title="Operations Guide")

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)

            assert doc["audience"] == "devops"
            assert doc["diataxis"] == "how-to"
            assert doc["meta"]["title"] == "Operations Guide"
            assert doc["meta"]["header"] == SAMPLE_HEADER
            assert len(doc["sections"]) == 2
            assert doc["sections"][0]["slug"] == "monitoring-alerting"
            assert doc["sections"][1]["slug"] == "deployment"
            assert "ETL run log" in doc["sections"][0]["body"]
            assert "CI/CD" in doc["sections"][1]["body"]
        finally:
            os.unlink(path)

    def test_title_extracted_from_header(self):
        """Title is extracted from header if not explicitly provided."""
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, [])
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            assert doc["meta"]["title"] == "Operations Guide"
        finally:
            os.unlink(path)

    def test_empty_sections(self):
        """Document with no sections is valid."""
        tree = build_xml_doc("end-users", "tutorial", "# Guide", [])
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            assert doc["sections"] == []
            assert doc["audience"] == "end-users"
        finally:
            os.unlink(path)

    def test_empty_refs(self):
        """Sections start with empty refs."""
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, SAMPLE_SECTIONS)
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            for section in doc["sections"]:
                assert section["refs"] == []
        finally:
            os.unlink(path)


class TestGetSectionSlugs:
    """get_section_slugs returns ordered slugs."""

    def test_returns_slugs_in_order(self):
        tree = build_xml_doc("devops", "how-to", "# Title", SAMPLE_SECTIONS)
        assert get_section_slugs(tree) == ["monitoring-alerting", "deployment"]

    def test_empty_document(self):
        tree = build_xml_doc("devops", "how-to", "# Title", [])
        assert get_section_slugs(tree) == []


class TestUpdateSectionBody:
    """update_section_body replaces CDATA body text."""

    def test_body_updated(self):
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, SAMPLE_SECTIONS)
        new_body = "<!-- section: monitoring-alerting -->\n## Monitoring & Alerting\n\nUpdated content here."
        update_section_body(tree, "monitoring-alerting", new_body)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            assert "Updated content here." in doc["sections"][0]["body"]
            # Other section unchanged
            assert "CI/CD" in doc["sections"][1]["body"]
        finally:
            os.unlink(path)

    def test_missing_slug_raises(self):
        tree = build_xml_doc("devops", "how-to", SAMPLE_HEADER, SAMPLE_SECTIONS)
        try:
            update_section_body(tree, "nonexistent", "body")
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert "nonexistent" in str(e)


class TestUpdateSectionRefs:
    """update_section_refs nests flat refs into XML structure."""

    def test_db_refs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", SAMPLE_SECTIONS)
        flat_refs = [
            {"type": "db", "schema": "road_runner", "table": "etl_runs", "column": "flow_name"},
            {"type": "db", "schema": "road_runner", "table": "etl_runs", "column": "status"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            assert refs[0] == {"type": "db", "schema": "road_runner", "table": "etl_runs", "column": "flow_name"}
            assert refs[1] == {"type": "db", "schema": "road_runner", "table": "etl_runs", "column": "status"}
        finally:
            os.unlink(path)

    def test_code_refs_class_and_function(self):
        tree = build_xml_doc("devops", "how-to", "# Title", SAMPLE_SECTIONS)
        flat_refs = [
            {"type": "code", "kind": "class", "name": "EtlRun", "attr": "status"},
            {"type": "code", "kind": "function", "name": "compute_finance_metrics",
             "module": "src/road_runner/flows/compute.py", "param": "recompute_stale"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            class_ref = refs[0]
            assert class_ref["type"] == "code"
            assert class_ref["kind"] == "class"
            assert class_ref["name"] == "EtlRun"
            assert class_ref["attr"] == "status"
            func_ref = refs[1]
            assert func_ref["type"] == "code"
            assert func_ref["kind"] == "function"
            assert func_ref["name"] == "compute_finance_metrics"
            assert func_ref["module"] == "src/road_runner/flows/compute.py"
            assert func_ref["param"] == "recompute_stale"
        finally:
            os.unlink(path)

    def test_flow_env_config_refs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", SAMPLE_SECTIONS)
        flat_refs = [
            {"type": "flow", "name": "ingest-quarterly-finance-data"},
            {"type": "env", "name": "WORKER_CONCURRENCY"},
            {"type": "config", "path": "config/field-mapping.yaml"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 3
            assert refs[0] == {"type": "flow", "name": "ingest-quarterly-finance-data"}
            assert refs[1] == {"type": "env", "name": "WORKER_CONCURRENCY"}
            assert refs[2] == {"type": "config", "path": "config/field-mapping.yaml"}
        finally:
            os.unlink(path)

    def test_enum_refs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", SAMPLE_SECTIONS)
        flat_refs = [
            {"type": "enum", "class": "EtlRun", "field": "status", "value": "completed"},
            {"type": "enum", "class": "EtlRun", "field": "status", "value": "failed"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 2
            assert refs[0] == {"type": "enum", "class": "EtlRun", "field": "status", "value": "completed"}
            assert refs[1] == {"type": "enum", "class": "EtlRun", "field": "status", "value": "failed"}
        finally:
            os.unlink(path)

    def test_mixed_refs_all_types(self):
        """All six ref types in one update."""
        tree = build_xml_doc("devops", "how-to", "# Title", SAMPLE_SECTIONS)
        flat_refs = [
            {"type": "db", "schema": "rr", "table": "runs", "column": "id"},
            {"type": "code", "kind": "class", "name": "Run"},
            {"type": "flow", "name": "ingest"},
            {"type": "env", "name": "PORT"},
            {"type": "config", "path": "config.yaml"},
            {"type": "enum", "class": "Run", "field": "status", "value": "ok"},
        ]
        update_section_refs(tree, "monitoring-alerting", flat_refs)

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            types = [r["type"] for r in refs]
            assert "db" in types
            assert "code" in types
            assert "flow" in types
            assert "env" in types
            assert "config" in types
            assert "enum" in types
        finally:
            os.unlink(path)

    def test_replace_existing_refs(self):
        """Updating refs replaces previous refs entirely."""
        tree = build_xml_doc("devops", "how-to", "# Title", SAMPLE_SECTIONS)
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "flow", "name": "old-flow"},
        ])
        update_section_refs(tree, "monitoring-alerting", [
            {"type": "flow", "name": "new-flow"},
        ])

        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            doc = parse_xml_doc(path)
            refs = doc["sections"][0]["refs"]
            assert len(refs) == 1
            assert refs[0]["name"] == "new-flow"
        finally:
            os.unlink(path)

    def test_missing_slug_raises(self):
        tree = build_xml_doc("devops", "how-to", "# Title", SAMPLE_SECTIONS)
        try:
            update_section_refs(tree, "nonexistent", [])
            assert False, "Should have raised ValueError"
        except ValueError as e:
            assert "nonexistent" in str(e)


class TestSerialize:
    """serialize_xml_doc writes valid XML."""

    def test_creates_parent_dirs(self):
        tree = build_xml_doc("devops", "how-to", "# Title", [])
        with tempfile.TemporaryDirectory() as td:
            path = os.path.join(td, "nested", "dir", "doc.xml")
            serialize_xml_doc(tree, path)
            assert os.path.isfile(path)
            # Verify it's parseable
            doc = parse_xml_doc(path)
            assert doc["audience"] == "devops"

    def test_atomic_write_no_leftover_tmp(self):
        """No .tmp file left after successful write."""
        tree = build_xml_doc("devops", "how-to", "# Title", [])
        with tempfile.NamedTemporaryFile(suffix=".xml", delete=False) as f:
            path = f.name
        try:
            serialize_xml_doc(tree, path)
            assert not os.path.exists(path + ".tmp")
        finally:
            os.unlink(path)
